// Recipes
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS';
export const RECIPE_SUCCESS = 'RECIPE_SUCCESS';